src/Entity/Messages.php
<?php

namespace App\Entity;

use App\Repository\MessagesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MessagesRepository::class)
 */
class Messages
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_read = 0;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="sent")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sender;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="received")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recipient;


    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }

    public function getSender(): ?Users
    {
        return $this->sender;
    }

    public function setSender(?Users $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getRecipient(): ?Users
    {
        return $this->recipient;
    }

    public function setRecipient(?Users $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }
}

src/Form/MessagesType.php
<?php

namespace App\Form;

use App\Entity\Messages;
use App\Entity\Users;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MessagesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            ->add('message', TextareaType::class, [
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            ->add('recipient', EntityType::class, [
                "class" => Users::class,
                "choice_label" => "email",
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            ->add("Envoyez", SubmitType::class, [
                "attr" => [
                    "class" => "btn btn-primary"
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Messages::class,
        ]);
    }
}

src/Controller/MessagesController.php
<?php

namespace App\Controller;

use App\Entity\Messages;
use App\Form\MessagesType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MessagesController extends AbstractController
{
    /**
     * @Route("/messages", name="messages")
     */
    public function index(): Response
    {
        return $this->render('messages/index.html.twig', [
            'controller_name' => 'MessagesController',
        ]);
    }

    /**
     * @Route("/send", name="send")
     */
    public function send(Request $request, ManagerRegistry $managerRegi): Response
    {
        $message = new Messages();

        $form = $this->createForm(MessagesType::class, $message);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $message->setSender($this->getUser());

            $em = $managerRegi->getManager();
            $em->persist($message);
            $em->flush();

            $this->addFlash(
                'message',
                'Message envoyez avec success'
            );

            return $this->redirectToRoute('messages');
        }

        return $this->render('messages/send.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/received", name="received")
     */
    public function received(): Response
    {
        return $this->render('messages/received.html.twig');
    }

    /**
     * @Route("/sent", name="sent")
     */
    public function sent(): Response
    {
        return $this->render('messages/sent.html.twig');
    }

    /**
     * @Route("/read/{id}", name="read")
     */
    public function read(Messages $message, ManagerRegistry $managerRegi): Response
    {
        $message->setIsRead(true);

        $em = $managerRegi->getManager();
        $em->persist($message);
        $em->flush();
        return $this->render('messages/read.html.twig', compact("message"));
    }

    /**
     * @Route("/delete/{id}", name="delete")
     */
    public function delete(Messages $message, ManagerRegistry $managerRegi): RedirectResponse
    {
        $em = $managerRegi->getManager();
        $em->remove($message);
        $em->flush();

        return $this->redirectToRoute('received');
    }
}

templates/messages/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}la messagerie
{% endblock %}

{% block body %}

	<section class="container">

		<div class="row">
			<div class="col">
				<h1>Messagerie</h1>
				<p>Resumer de la messagerie</p>
				<p>Recus :{{ app.user.received|length }}</p>
				<p>Envoyé :{{ app.user.sent|length }}</p>
				<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
					Voire mes dossiers
				</a>
                <a href="" class="btn btn-primary">Envoyez un message</a>
			</div>
		</div>
		<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
			<div class="offcanvas-header">
				<h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
				<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
			</div>
			<div class="offcanvas-body">
				<div class="list-group">
					<a href="{{ path("messages") }}" class="list-group-item list-group-item-action active">Accueil</a>
				</div>
				<div class="list-group">
					<a href="{{ path("received") }}" class="list-group-item list-group-item-action">Boite de reception</a>
				</div>
				<div class="list-group">
					<a href="{{ path("sent") }}" class="list-group-item list-group-item-action">Elements envoyé</a>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

templates/messages/read.html.twig
{% extends 'base.html.twig' %}

{% block title %}la messagerie
{% endblock %}

{% block body %}

	<section class="container">
		<div class="row">
			<div class="col-12">
				<h1>Messagerie</h1>
				<h2>{{message.title}}</h2>
				<p>Message de
					{{ message.sender.email }}</p>
				<p>Envoyer le
					{{ message.createdAt|date("m/d/Y") }}</p>
				<div>
					{{ message.message }}
				</div>
				<div>
					<div>
						<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
							Voire mes dossiers
						</a>
						<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
							Repondre
						</a>
						<a class="btn btn-primary" data-bs-toggle="offcanvas" href="{{ path("messages")}}" role="button" aria-controls="offcanvasExample">
							Retour
						</a>
					</div>
				</div>
				<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
					<div class="offcanvas-header">
						<h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
						<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
					</div>
					<div class="offcanvas-body">
						<div class="list-group">
							<a href="{{ path("messages") }}" class="list-group-item list-group-item-action ">Accueil</a>
						</div>
						<div class="list-group">
							<a href="{{ path("received") }}" class="list-group-item list-group-item-action active">Boite de reception</a>
						</div>
						<div class="list-group">
							<a href="{{ path("sent") }}" class="list-group-item list-group-item-action ">Elements envoyé</a>
						</div>
					</div>
				</div>
			</section>
		{% endblock %}

templates/messages/received.html.twig
{% extends 'base.html.twig' %}

{% block title %}la messagerie
{% endblock %}

{% block body %}

	<section class="container">
		<div class="row">
			<div class="col-12">
				<h1>Messagerie</h1>
				<h2>Boite de reception</h2>
				<p>Vous avez recus :{{ app.user.received|length }}
					messages</p>
			</div>
			<div class="col-3">De</div>
			<div class="col-3">Sujet</div>
			<div class="col-3">Date</div>
			<div class="col-3">Actions</div>
			{% for message in app.user.received %}

				{% if message.isRead == 0 %}
					{% set bold = "fw-bold" %}
				{% else %}
					{% set bold = "" %}
				{% endif %}

				<div class="col-3 {{ bold }}">{{ message.sender.email }}</div>
				<div class="col-3 {{ bold }}">
					<a href="{{ path("read", {"id": message.id}) }}">
						{{ message.title }}
					</a>
				</div>
				<div class="col-3 {{ bold }}">{{ message.createdAt|date("m/d/Y") }}</div>
				<div class="col-3">
					<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-x-fill text-danger" viewbox="0 0 16 16">
						<path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.026A2 2 0 0 0 2 14h6.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.606-3.446l-.367-.225L8 9.586l-1.239-.757ZM16 4.697v4.974A4.491 4.491 0 0 0 12.5 8a4.49 4.49 0 0 0-1.965.45l-.338-.207L16 4.697Z"/>
						<path d="M16 12.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0Zm-4.854-1.354a.5.5 0 0 0 0 .708l.647.646-.647.646a.5.5 0 0 0 .708.708l.646-.647.646.647a.5.5 0 0 0 .708-.708l-.647-.646.647-.646a.5.5 0 0 0-.708-.708l-.646.647-.646-.647a.5.5 0 0 0-.708 0Z"/>
					</svg>
				</div>
			{% endfor %}
			<div>
				<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
					Voir mes dossiers
				</a>
				<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
					Envoyez un message
				</a>
			</div>
		</div>
		<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
			<div class="offcanvas-header">
				<h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
				<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
			</div>
			<div class="offcanvas-body">
				<div class="list-group">
					<a href="{{ path("messages") }}" class="list-group-item list-group-item-action ">Accueil</a>
				</div>
				<div class="list-group">
					<a href="{{ path("received") }}" class="list-group-item list-group-item-action active">Boite de reception</a>
				</div>
				<div class="list-group">
					<a href="{{ path("send") }}" class="list-group-item list-group-item-action ">Elements envoyé</a>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

templates/messages/send.html.twig
{% extends 'base.html.twig' %}

{% block title %}la messagerie
{% endblock %}

{% block body %}

	<section class="container">
		<div class="row">
			<div class="col">
				<h1>Messagerie</h1>
				{{ form(form) }}
				<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
					Voire mes dossiers
				</a>
			</div>
		</div>
		<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
			<div class="offcanvas-header">
				<h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
				<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
			</div>
			<div class="offcanvas-body">
				<div class="list-group">
					<a href="{{ path("messages") }}" class="list-group-item list-group-item-action ">Accueil</a>
				</div>
				<div class="list-group">
					<a href="{{ path("received") }}" class="list-group-item list-group-item-action">Boite de reception</a>
				</div>
				<div class="list-group">
					<a href="{{ path("sent") }}" class="list-group-item list-group-item-action active">Elements envoyé</a>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

templates/messages/sent.html.twig
{% extends 'base.html.twig' %}

{% block title %}la messagerie
{% endblock %}

{% block body %}

	<section class="container">
		<div class="row">
			<div class="col-12">
				<h1>Messagerie</h1>
				<h2>Boite d'envois</h2>
				<p>Vous avez envoyé :{{ app.user.sent|length }}
					messages</p>
			</div>
			<div class="col-3">De</div>
			<div class="col-3">Sujet</div>
			<div class="col-3">Date</div>
			<div class="col-3">Actions</div>
			{% for message in app.user.sent %}

				{% if message.isRead == 0 %}
					{% set bold = "fw-bold" %}
				{% else %}
					{% set bold = "" %}
				{% endif %}

				<div class="col-3 {{ bold }}">{{ message.sender.email }}</div>
				<div class="col-3 {{ bold }}">
					<a href="{{ path("read", {"id": message.id}) }}">
						{{ message.title }}
					</a>
				</div>
				<div class="col-3 {{ bold }}">{{ message.createdAt|date("m/d/Y") }}</div>
				<div class="col-3" >
				<a href="{{ path("delete", {"id": message.id}) }}">
					<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-x-fill text-danger" viewbox="0 0 16 16">
						<path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.026A2 2 0 0 0 2 14h6.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.606-3.446l-.367-.225L8 9.586l-1.239-.757ZM16 4.697v4.974A4.491 4.491 0 0 0 12.5 8a4.49 4.49 0 0 0-1.965.45l-.338-.207L16 4.697Z"/>
						<path d="M16 12.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0Zm-4.854-1.354a.5.5 0 0 0 0 .708l.647.646-.647.646a.5.5 0 0 0 .708.708l.646-.647.646.647a.5.5 0 0 0 .708-.708l-.647-.646.647-.646a.5.5 0 0 0-.708-.708l-.646.647-.646-.647a.5.5 0 0 0-.708 0Z"/>
					</svg>
				</div>
				</a>
			{% endfor %}
			<div>
				<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
					Voir mes dossiers
				</a>
				<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
					Envoyez un message
				</a>
			</div>
		</div>
		<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
			<div class="offcanvas-header">
				<h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
				<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
			</div>
			<div class="offcanvas-body">
				<div class="list-group">
					<a href="{{ path("messages") }}" class="list-group-item list-group-item-action ">Accueil</a>
				</div>
				<div class="list-group">
					<a href="{{ path("received") }}" class="list-group-item list-group-item-action ">Boite de reception</a>
				</div>
				<div class="list-group">
					<a href="{{ path("sent") }}" class="list-group-item list-group-item-action active">Elements envoyé</a>
				</div>
			</div>
		</div>
	</section>
{% endblock %}